server:
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 500

spring:
  datasource:
    url: jdbc:h2:mem:spring-jwt-auth-boilerplate
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true